# Generated by Django 6.0 on 2025-12-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='category',
            new_name='news_category',
        ),
        migrations.AlterField(
            model_name='news',
            name='news_text',
            field=models.TextField(verbose_name='Опишите новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_name',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
