# Generated by Django 6.0 on 2026-01-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_category_news_news_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_video',
            field=models.FileField(default='', upload_to='media', verbose_name='Видео'),
        ),
    ]
